language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0
      - python3
      - python3-pip
      - python3-setuptools
      - gperf

jobs:
  include:
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="msat" OPTS="--auto-yes"
    - os: linux
      dist: bionic
      env: SOLVER="yices2" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="yices2" OPTS=""
      compiler: clang
    - os: osx
      osx_image: xcode12
      env: SOLVER='btor' OPTS=""
    - os: osx
      osx_image: xcode12
      env: SOLVER='cvc4' OPTS=""
    - os: osx
      osx_image: xcode12
      env: SOLVER='msat' OPTS="--auto-yes"
    - os: osx
      osx_image: xcode12
      env: SOLVER='yices2' OPTS=""

script:
  # brew sometimes fails on something after the python installation -- but we don't want the build to fail
  - ./travis-scripts/travis-setup-osx-python.sh || true
  - sudo python3 -m pip install Cython==0.29 --install-option="--no-cython-compile"
  - sudo python3 -m pip install pytest
  # Temporarily download CVC4 instead of building it
  # There's some issue on mac with get-antlr-3.4
  - |
    if [ $SOLVER == "cvc4" ]; then
        ./travis-scripts/download-cvc4.sh;
    else
        ./travis-scripts/setup-${SOLVER}.sh ${OPTS}
    fi
  - bash -c "./contrib/setup-skbuild.sh"
  - bash -c "./configure.sh --debug --${SOLVER} --python"
  - bash -c "cd build && make -j && make test && pip install -e ./python/smt_switch && cd ../ && pytest ./tests/"
  # Removing wheels test to speed up Travis builds
  # TODO consider building wheels in a separate configuration
  # install wheels
  # - sudo python3 -m pip install wheel setuptools virtualenv
  # - python3 contrib/wheels/build_wheel.py bdist_wheel
  # - bash -c "python3 -m virtualenv env && source env/bin/activate && pip install dist/* pytest && pytest tests/"
