language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0
      - python3
      - python3-pip
      - python3-setuptools
      - gperf

jobs:
  include:
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="msat" OPTS="--auto-yes"
    - os: linux
      dist: bionic
      env: SOLVER="yices2" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="yices2" OPTS=""
      compiler: clang
    - os: osx
      osx_image: xcode9
      env: SOLVER='btor' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='cvc4' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='msat' OPTS="--auto-yes"
    - os: osx
      osx_image: xcode9
      env: SOLVER='yices2' OPTS=""

script:
  # brew sometimes fails on something after the python installation -- but we don't want the build to fail
  - ./scripts/travis-setup-osx-python.sh || true
  - sudo python3 -m pip install Cython==0.29 --install-option="--no-cython-compile"
  - bash -c "./contrib/setup-${SOLVER}.sh ${OPTS}"
  - bash -c "./configure.sh --${SOLVER} --python"
  - bash -c "cd build && make -j && make test"
  # install wheels
  - sudo python3 -m pip install wheel setuptools virtualenv
  - python3 contrib/wheels/build_wheel.py bdist_wheel
  - bash -c "python3 -m virtualenv env && source env/bin/activate && pip install dist/* pytest && pytest tests/"
