name: Python Wheels

on:
  push:
    tags:
      - '*'


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [35, 36, 37, 38]

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgmp-dev \
          libedit-dev
        python3 -m pip install toml
        python3 -m pip install setuptools
        python3 -m pip install pexpect
        python3 -m pip install wheel
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build wheels
      shell: bash
      run: |
        ./contrib/wheels/ci.sh
          # docker run --mount type=bind,source="$(pwd)"/../smt-switch,target=/smt-switch keyiz/manylinux-java:py${{ matrix.python-version }} /smt-switch/contrib/wheels/ci.sh
      env:
        PY_VERSION: ${{ matrix.python-version }}
    - uses: actions/upload-artifact@v1
      with:
        name: py${{ matrix.python-version }} wheel
        path: wheelhouse/
    - name: Installing Python packages
      shell: bash
      run: |
          sudo pip3 install setuptools
          sudo pip3 install twine
    - name: Uploading to PyPi
      shell: bash
      run: |
          echo [distutils]                                  > ~/.pypirc
          echo index-servers =                             >> ~/.pypirc
          echo "  pypi"                                    >> ~/.pypirc
          echo                                             >> ~/.pypirc
          echo [pypi]                                      >> ~/.pypirc
          echo repository=https://upload.pypi.org/legacy/  >> ~/.pypirc
          echo username=makaim                             >> ~/.pypirc
          echo password=$PYPI_PASSWORD                     >> ~/.pypirc
          twine upload --config-file ~/.pypirc --skip-existing wheelhouse/*
      env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
